dist: trusty
sudo: required
language: node_js
node_js:
    - 7.6.0

env:       
    global:
        - PASS=""
        - NODE_USER=root
        - USER=root
services: 
    - mysql
    - redis-server
    - elasticsearch
before_install:
    - sudo apt-get -y update
    - gem install redis

cache:
    directories:
        - node_modules
install:
    - npm install
    - npm update --save 
    - npm prune
    - npm dedupe 
    - npm shrinkwrap 

before_script:
    - npm install -g express-generator@4.15.0 gulp@3.9.1 mocha@3.5.0 siege@0.2.0
    - npm install -g trucker@0.7.3 webpack@3.4.1 istanbul@0.4.5 jshint@2.9.5
    - jshint app/ microservices/ routes/ run/ test/ util/ public/javascripts/service public/javascripts/viewmodel/ public/javascripts/view public/javascripts/js/home-setup.js public/javascripts/chat_render.js public/javascripts/chatViewModel.js
    #elastic search takes a while to start, sleep for some time
    - sleep 10

script: ./test.sh
